// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguraVida.Claims.Infrastructure.Persistence;

#nullable disable

namespace SeguraVida.Claims.Infrastructure.Persistence.Migrations;

    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260605204614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeguraVida.Claims.Domain.Claims.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("claim_id");

                    b.Property<string>("AdjustmentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("peritaje_notes");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("approved_amount");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("claim_number");

                    b.Property<decimal>("ClaimedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("claimed_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("NormalizedDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("normalized_description");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<DateOnly>("ReportedAt")
                        .HasColumnType("date")
                        .HasColumnName("reported_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_CLAIM_CLAIM_NUMBER");

                    b.HasIndex("IncidentDate")
                        .HasDatabaseName("IX_CLAIM_INCIDENT_DATE");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("IX_CLAIM_POLICY_ID");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("IX_CLAIM_REPORTED_DATE");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CLAIM_STATUS");

                    b.ToTable("CLAIM", (string)null);
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Claims.ClaimStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("history_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("claim_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("new_status");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("IX_CLAIM_STATUS_HISTORY_CLAIM_ID");

                    b.ToTable("CLAIM_STATUS_HISTORY", (string)null);
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Parties.InsuredParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("party_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("document_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("IX_INSURED_PARTY_DOCUMENT_ID");

                    b.ToTable("INSURED_PARTY", (string)null);
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Policies.InsurancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("branch");

                    b.Property<Guid>("HolderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("holder_id");

                    b.Property<decimal>("InsuredAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("insured_amount");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("policy_number");

                    b.Property<decimal>("Premium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("premium");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.HasKey("Id");

                    b.HasIndex("HolderId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_POLICY_POLICY_NUMBER");

                    b.ToTable("POLICY", (string)null);
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Claims.Claim", b =>
                {
                    b.HasOne("SeguraVida.Claims.Domain.Policies.InsurancePolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Claims.ClaimStatusHistory", b =>
                {
                    b.HasOne("SeguraVida.Claims.Domain.Claims.Claim", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Policies.InsurancePolicy", b =>
                {
                    b.HasOne("SeguraVida.Claims.Domain.Parties.InsuredParty", null)
                        .WithMany()
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeguraVida.Claims.Domain.Claims.Claim", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
}
